version: "3"


services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - postgres

  django:
    build:
      context: ./site
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./site:/usr/src/smm-group/site
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - postgres

  nginx:
    image: "nginx:latest"
    restart: unless-stopped
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./site:/usr/src/smm-group/backend
    depends_on:
      - django
      - db
    ports:
      - "80:80"
      - "443:443"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
