# Generated by Django 3.0.5 on 2020-07-12 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('data', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='PricesForServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('social_network', models.CharField(choices=[('fa', 'Facebook'), ('vk', 'Vkontakte'), ('in', 'Instagram'), ('yo', 'YouTube'), ('tw', 'Twitch'), ('ok', 'Ok')], max_length=2)),
                ('name_service', models.CharField(choices=[('na', 'Накрутка живых подписчиков'), ('la', 'Лайки'), ('pr', 'Просмотры')], max_length=2)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'цена за услугу',
                'verbose_name_plural': 'цены за услуги',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('fa', 'Facebook'), ('vk', 'Vkontakte'), ('in', 'Instagram'), ('yo', 'YouTube'), ('tw', 'Twitch'), ('ok', 'Ok')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('social_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SocialNetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Это поле обязательно', max_length=254)),
                ('balance', models.IntegerField(default=0)),
                ('ref_link', models.CharField(max_length=8)),
                ('secret_key', models.CharField(blank=True, max_length=8, null=True)),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('social_network', models.CharField(max_length=200)),
                ('name_service', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=2000)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.BooleanField()),
                ('price', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Profile')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
