# Generated by Django 3.0.5 on 2020-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200719_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=55)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['social_network']},
        ),
        migrations.AlterField(
            model_name='service',
            name='social_network',
            field=models.CharField(choices=[('fa', 'Facebook'), ('vk', 'Vkontakte'), ('in', 'Instagram'), ('yo', 'YouTube'), ('tw', 'Twitch'), ('ok', 'Ok')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
    ]
