# Generated by Django 3.2.14 on 2022-08-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220805_0048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsModel',
        ),
    ]
