# Generated by Django 3.2.14 on 2022-08-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_newsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Quest_Answer',
        ),
    ]
