# Generated by Django 3.2.14 on 2022-08-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220807_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PricesForServices',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
