# Generated by Django 3.2.14 on 2022-08-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricesForServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('social_network', models.CharField(choices=[('fa', 'Facebook'), ('vk', 'Vkontakte'), ('in', 'Instagram'), ('yo', 'YouTube'), ('tw', 'Twitch'), ('ok', 'Ok')], max_length=2)),
                ('name_service', models.CharField(choices=[('na', 'Накрутка живых подписчиков'), ('la', 'Лайки'), ('pr', 'Просмотры')], max_length=2)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'цена за услугу',
                'verbose_name_plural': 'цены за услуги',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('price', models.FloatField()),
                ('social_network', models.CharField(choices=[('fa', 'Facebook'), ('vk', 'Vkontakte'), ('in', 'Instagram'), ('yo', 'YouTube'), ('tw', 'Twitch'), ('ok', 'Ok')], max_length=2)),
            ],
            options={
                'ordering': ['social_network'],
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('num_serv', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('social_network', models.CharField(max_length=200)),
                ('name_service', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=2000)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.BooleanField()),
                ('price', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.profile')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
